apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-rs
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: init-rs
          image: mongo:7

          command:
            - /bin/bash
            - -c
            - |

              until getent hosts mongodb-0.mongodb mongodb-1.mongodb mongodb-2.mongodb; do
                echo "Esperando DNS de los pods..."
                sleep 2
              done

              mongosh --host mongodb-0.mongodb:27017 <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  {_id: 0, host: "mongodb-0.mongodb:27017"},
                  {_id: 1, host: "mongodb-1.mongodb:27017"},
                  {_id: 2, host: "mongodb-2.mongodb:27017"}
                ]
              })
              EOF

              echo "Esperando PRIMARY..."

              until mongosh --host mongodb-0.mongodb:27017 --quiet --eval "db.hello().isWritablePrimary" | grep true
              do
                sleep 2
              done

              echo "ReplicaSet creado correctamente."
