#04-cluster-init-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: redis-init
        image: redis:7.2
        command:
        - /bin/sh
        - -c
        - |
          sleep 20
          yes yes | redis-cli --cluster create \
          redis-0.redis-headless:6379 \
          redis-1.redis-headless:6379 \
          redis-2.redis-headless:6379 \
          --cluster-yes
