apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: keycloak
  password: keycloak-pass

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
